#!/usr/bin/env python3
"""Convert llama2.c's legacy stories260K checkpoint to OpenLLM OCQ8.

OCQ8 is deliberately row-addressable: every matrix row is [float32 scale,
int8 values].  The OpenComputers runtime can therefore seek directly to one
row, dot it with the current activation, and discard the bytes immediately.
"""
from __future__ import annotations

import argparse
import hashlib
import math
import struct
from pathlib import Path

HEADER = 256
MAGIC = b"OCQ8"


def read_floats(handle, count: int) -> list[float]:
    raw = handle.read(count * 4)
    if len(raw) != count * 4:
        raise ValueError("checkpoint ended before all expected weights")
    return list(struct.unpack("<%df" % count, raw))


def write_rows(out, values: list[float], rows: int, columns: int) -> tuple[float, float]:
    """Write per-row symmetric INT8 weights; return max and mean errors."""
    maximum_error = 0.0
    error_sum = 0.0
    elements = 0
    for row in range(rows):
        start = row * columns
        source = values[start:start + columns]
        peak = max((abs(v) for v in source), default=0.0)
        scale = peak / 127.0 if peak else 1.0
        q = [max(-127, min(127, int(math.floor(v / scale + 0.5)) if v >= 0 else int(math.ceil(v / scale - 0.5)))) for v in source]
        out.write(struct.pack("<f", scale))
        out.write(struct.pack("<%db" % columns, *q))
        for original, quantized in zip(source, q):
            error = abs(original - quantized * scale)
            maximum_error = max(maximum_error, error)
            error_sum += error
            elements += 1
    return maximum_error, error_sum / max(elements, 1)


def write_config(path: Path, p: tuple[int, ...], shared: bool, model_bytes: int) -> None:
    dim, hidden, layers, heads, kv_heads, vocab, seq_len = p
    text = """-- Generated by tools/convert_model.py. Do not edit by hand.\nreturn {\n  format = \"OCQ8\",\n  version = 1,\n  dim = %d, hidden_dim = %d, n_layers = %d, n_heads = %d,\n  n_kv_heads = %d, vocab_size = %d, max_seq_len = %d,\n  shared_classifier = %s,\n  context_length = 16,\n  model_bytes = %d,\n}\n""" % (dim, hidden, layers, heads, kv_heads, vocab, seq_len, "true" if shared else "false", model_bytes)
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path, help="legacy llama2.c .bin checkpoint")
    parser.add_argument("output", type=Path, help="output OCQ8 model.bin")
    parser.add_argument("--config", type=Path, help="generated config.lua")
    args = parser.parse_args()

    with args.input.open("rb") as src:
        header = src.read(28)
        if len(header) != 28:
            raise ValueError("not a legacy llama2.c checkpoint")
        dim, hidden, layers, heads, kv_heads, raw_vocab, seq_len = struct.unpack("<7i", header)
        shared = raw_vocab > 0
        vocab = abs(raw_vocab)
        if not (dim > 0 and hidden > 0 and layers > 0 and heads > 0 and kv_heads > 0 and vocab > 0):
            raise ValueError("invalid checkpoint header")
        if dim % heads or heads % kv_heads:
            raise ValueError("unsupported attention dimensions")
        p = (dim, hidden, layers, heads, kv_heads, vocab, seq_len)
        kv_dim = dim * kv_heads // heads

        # The legacy order is fixed by llama2.c's memory_map_weights.
        embeddings = read_floats(src, vocab * dim)
        rms_att = read_floats(src, layers * dim)
        wq = read_floats(src, layers * dim * dim)
        wk = read_floats(src, layers * kv_dim * dim)
        wv = read_floats(src, layers * kv_dim * dim)
        wo = read_floats(src, layers * dim * dim)
        rms_ffn = read_floats(src, layers * dim)
        w1 = read_floats(src, layers * hidden * dim)
        w2 = read_floats(src, layers * dim * hidden)
        w3 = read_floats(src, layers * hidden * dim)
        rms_final = read_floats(src, dim)
        # RoPE lookup tables are intentionally skipped: the OC runtime computes
        # the same formula on demand and does not need 32 KiB of stored tables.
        read_floats(src, seq_len * (dim // heads) // 2)
        read_floats(src, seq_len * (dim // heads) // 2)
        classifier = None if shared else read_floats(src, vocab * dim)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    max_error = mean_error = 0.0
    with args.output.open("wb") as out:
        header = struct.pack("<4sI7IB", MAGIC, 1, dim, hidden, layers, heads, kv_heads, vocab, seq_len, int(shared))
        out.write(header + b"\0" * (HEADER - len(header)))
        out.write(struct.pack("<%df" % len(rms_att), *rms_att))
        out.write(struct.pack("<%df" % len(rms_ffn), *rms_ffn))
        out.write(struct.pack("<%df" % len(rms_final), *rms_final))
        matrices = [
            (embeddings, vocab, dim),
            (wq, layers * dim, dim), (wk, layers * kv_dim, dim),
            (wv, layers * kv_dim, dim), (wo, layers * dim, dim),
            (w1, layers * hidden, dim), (w2, layers * dim, hidden), (w3, layers * hidden, dim),
        ]
        if classifier is not None:
            matrices.append((classifier, vocab, dim))
        for values, rows, columns in matrices:
            mx, avg = write_rows(out, values, rows, columns)
            max_error = max(max_error, mx)
            mean_error = max(mean_error, avg)

    actual = args.output.stat().st_size
    if args.config:
        write_config(args.config, p, shared, actual)
    sha = hashlib.sha256(args.output.read_bytes()).hexdigest()
    args.output.with_suffix(args.output.suffix + ".sha256").write_text(sha + "  " + args.output.name + "\n", encoding="ascii")
    print("wrote", args.output, actual, "bytes")
    print("row INT8 max reconstruction error %.8f; largest matrix mean error %.8f" % (max_error, mean_error))
    print("sha256", sha)


if __name__ == "__main__":
    main()
